workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Generate Gradle wrapper (if missing)
        script: gradle wrapper --gradle-version 8.4 || true
      - name: Set Gradle permissions
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sachinkashyap47143@gmail.com
